default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  timeout: 5000
  username: deployment
  password: <%= ENV['VPS_PASS'] %>

development:
  <<: *default
  database: apart_crime_dev

test:
  <<: *default
  database: apart_crime_test

production:
  <<: *default
  database: apart_crime_prod
